---
- name: Configure VM with Filebeat
  hosts: webservers
  remote_user: arvidsaur
  become: true
  tasks:
    - name: Download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install filebeat deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Copy
      ansible.builtin.copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable filebeat system module
      command: filebeat modules enable system

    - name: Setup filebeat
      command: filebeat setup

    - name: Start filebeat
      command: service filebeat start

    - name: Use systemd module to enable filebeat
      systemd:
        name: filebeat
        enabled: yes


