---
- name: Configure VM with Metricbeat
  hosts: webservers
  remote_user: arvidsaur
  become: true
  tasks:
    - name: Download metricbeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install metricbeat deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy
      ansible.builtin.copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable metricbeat docker module
      command: metricbeat modules enable docker

    - name: Setup metricbeat
      command: metricbeat setup

    - name: Start metricbeat
      command: service metricbeat start

    - name: Use systemd module to enable metricbeat
      systemd:
        name: metricbeat
        enabled: yes


